
all_openers = [
  "You look like something's on your mind.",
  "Trouble following you down here tonight?",
  "You look like you're carrying more than a drink.",
  "That look - something weighing you down?",
  "Whatever's chasing you, it hasn't caught you yet.",
  "Noticed the pause in your eyes. Want to fill it?",
  "Something you're not saying. Want to try?",
  "Let me know if that drink isn't strong enough for what's on your mind.",
  "You're stirring more than your glass.",
  "Whatever's circling you, it followed you in.",
  "I've seen that look before - usually before something breaks.",
  "Looks like your drink isn't the only thing that needs settling.",
  "Looks like you've got more on your plate than that drink.",
  "No metrics down here. You can say it.",
  "Something's off - in you, not the drink.",
  "You're not here for the cocktails, are you?",
  "Something you left unsaid. Still time.",
  "Bar's a good place for dilemmas. Want to test that?",
  "You're carrying a decision, aren't you?",
  "Whatever's heavy - you don't have to hold it alone.",
  "You look like you know something you wish you didn't.",
  "Drink's honest. You can be too.",
  "You're here, but not really. What's pulling you back?",
  "That exhale - something behind it?",
  "No council ears here. You're safe.",
  "You seem like you've seen something no one else has.",
  "You're bracing for something. Want to talk before it hits?",
  "Want to test a thought out loud?",
  "Whatever's wrong - you're not the first to bring it here.",
  "Something you can't say up there?",
  "You keeping something safe, or keeping it secret?",
  "Feel like you're hiding from a truth?",
  "Some thoughts are safer in the dark. Want to try?",
  "The drink is simple. You're not.",
  "There's a question on your face. Want to ask it?",
  "You're pacing inside. Want to unpack it?",
  "Looks like a choice is chasing you.",
  "Hard to carry questions alone. Want help?",
  "Want to talk about what the drink isn't touching?",
  "You okay if I ask what's really bothering you?",
  "Feels like you're hiding from more than cameras.",
  "Looks like part of you stayed outside.",
  "Looks like someone asked you a question you haven't answered yet."
]
