all_openers = [
    "Hey, how's it going?",
    "Long night?",
    "You made it, didn't you?",
    "Is it quiet tonight?",
    "Still dry outside?",
    "No cameras up there, right?",
    "Is the smoke thicker today?",
    "No signals reach here, do they?",
    "Is the city loud today?",
    "Did you walk the long way?",
    "Still breathing in Stenograd?",
    "Are the systems feeling jumpy?",
    "Are the lines starting to blur?",
    "Storm above us?",
    "They still scanning topside?",
    "Same boots, different dust - right?",
    "Is the air heavier today?",
    "You still trust your steps?",
    "Does the city feel colder?",
    "Did you make it through the day?",
    "You look like you've seen some things - rough day?",
    "Rough one out there?",
    "City treating you alright?",
    "Long walk to get here?",
    "You keeping steady?",
    "Quiet night, huh?",
    "Looks like you needed a pause - that right?",
    "Everything holding up okay?",
    "Feel like a slow night to you?",
    "Got out before the rush?",
    "You alright?",
    "One of those days?",
    "Feels cooler down here, doesn't it?",
    "Is the whole city running hot today?",
    "Did you make it through the noise?",
    "Are people restless tonight?",
    "Something bring you down here?",
    "No trouble getting here?",
    "Is the city acting weird lately?",
    "Timing's good - not too busy, huh?",
    "Everything feel off today?",
    "You're not here by accident, are you?",
    "Heard the streets are tense again?",
    "Did the city spit you out again?",
    "Do the streets feel heavier today?",
    "How's the path down here?",
    "Night's only just started, hasn't it?",
    "Same city, different story - yeah?",
    "Another quiet night for you?",
    "Did you time it well - calm right now?",
    "City been kind to you?",
    "You look like you dodged something - true?",
    "Is it always this quiet when you come in?",
    "You know your way around down here?",
    "Still breathing, aren't you?",
    "You feel it too - something's off, right?",
    "Everything outside still spinning?",
    "You made it in one piece?",
    "It's one of those nights, isn't it?",
    "Did you slip in easy tonight?",
    "Is your night just starting or ending?"
]