
all_openers = [
  "Yeah... makes me wonder how your week's been.",
  "Sounds like you've had a lot going on lately, huh?",
  "I get that - been a strange stretch of days for you too?",
  "Kinda feels like things haven't been normal for a while. You noticing that?",
  "Funny how things shift without anyone saying much. You seen that around you?",
  "Feels like everyone's on edge. You too?",
  "Things still feel steady in your world?",
  "You get the sense something's been building lately?",
  "You ever feel like the air's just... heavier now?",
  "Makes me wonder what your days have been like recently.",
  "Can't help but feel like everyone's carrying something these days. You too?",
  "You notice people acting different lately?",
  "Been a while since things felt predictable, huh?",
  "You still keeping the same rhythm, or things gotten weird?",
  "That makes me think - what's been different for you lately?",
  "Feels like there's a story behind that tone. You alright?",
  "I've been hearing strange little things all week. Any make their way into your life?",
  "Ever get that feeling like the ground's shifting just a little under everything?",
  "Makes me think - how's life been treating you these days?",
  "I can't tell if it's just me or if the city's... changed. What's it feel like to you?",
  "You keeping out of the mess, or does it keep finding you?",
  "You still feeling like yourself lately?",
  "Not sure if it's just the weather or something else, but people seem different. You notice that?",
  "You seem like someone who notices things. What've you been picking up on lately?",
  "It's been a rough season for some. You managing okay?",
  "You getting by alright with everything swirling around?",
  "You ever get tired of pretending things are fine?",
  "Hard to keep track of what's normal anymore. What's that look like for you?",
  "You ever feel like you're walking a little more carefully these days?",
  "Whatever's been going on, seems like you've been managing it quietly.",
  "Folks don't always talk, but they carry plenty. You carrying much these days?"
]